//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Operation
    {
        public int Id { get; set; }
        [Display(Name = "Operation Name")]
        public string Operation1 { get; set; }
        public System.DateTime Date { get; set; }
        public string Table { get; set; }
        public string Description { get; set; }
    }
}
