//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [StringLength(20, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string ProductCode { get; set; }
        public int IdSupplier { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
