//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int ID { get; set; }
        [StringLength(20, MinimumLength = 3)]
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        [RegularExpression(@"[a-zA-Z""'\s-]*$")]
        [StringLength(20, MinimumLength = 3)]
        [Required]
        public string Login { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte[] AvatarImage { get; set; }
    }
}
