USE [master]
GO

/****** Object:  Database [dbfirst]    Script Date: 7/18/2018 1:58:47 PM ******/
CREATE DATABASE [dbfirst]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbfirst', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbfirst.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbfirst_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbfirst_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbfirst].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbfirst] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbfirst] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbfirst] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbfirst] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbfirst] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbfirst] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbfirst] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbfirst] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbfirst] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbfirst] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbfirst] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbfirst] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbfirst] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbfirst] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbfirst] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dbfirst] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbfirst] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbfirst] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbfirst] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbfirst] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbfirst] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbfirst] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbfirst] SET RECOVERY FULL 
GO

ALTER DATABASE [dbfirst] SET  MULTI_USER 
GO

ALTER DATABASE [dbfirst] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbfirst] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbfirst] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbfirst] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbfirst] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbfirst] SET  READ_WRITE 
GO

