USE [master]
GO

/****** Object:  Database [StoreManagement]    Script Date: 7/18/2018 1:59:01 PM ******/
CREATE DATABASE [StoreManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StoreManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StoreManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StoreManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StoreManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StoreManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StoreManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StoreManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StoreManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StoreManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StoreManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [StoreManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StoreManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StoreManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StoreManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StoreManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StoreManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StoreManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StoreManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StoreManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StoreManagement] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StoreManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StoreManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StoreManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StoreManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StoreManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StoreManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StoreManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StoreManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [StoreManagement] SET  MULTI_USER 
GO

ALTER DATABASE [StoreManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StoreManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StoreManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StoreManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StoreManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StoreManagement] SET  READ_WRITE 
GO

